name: Continuous Integration

env:
  NODE_VERSION: 16

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        shell: bash
        run: |
          npm i pnpm -g

      - name: Install Dependencies
        shell: bash
        run: |
          pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        shell: bash
        run: |
          pnpm run lint

  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

        - name: Cache .pnpm-store
          uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}

        - name: Install pnpm
          shell: bash
          run: |
            npm i pnpm -g

        - name: Install Dependencies
          shell: bash
          run: |
            pnpm install --frozen-lockfile
          env:
            CI: true

      - name: Test
        shell: bash
        run: |
          pnpm run test
